Test.Web/Controllers/CommitteeGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SparshWeb.CustomAttribute;
using SparshWeb.Models;
using Test.Web.ModelBusiness;

namespace Test.Web.Controllers
{
    public class CommitteeGroupController : Controller
    {
        // GET: CommitteeGroup
        [CustomAuthentication]
        public ActionResult Index(int? page)
        {
            List<CommitteeGroupViewModel> cgList = CommitteeGroupsBusiness.GetAllCommitteeGroupList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(cgList.ToPagedList(pageNumber, pageSize));
        }

        // GET: CommitteeGroup/Details/5
        [CustomAuthentication]
        public ActionResult Details(int id)
        {
            CommitteeGroupViewModel model = CommitteeGroupsBusiness.DetailsCommitteeGroup(id);
            return View(model);
        }

        // GET: CommitteeGroup/Create
        [CustomAuthentication]
        public ActionResult Create()
        {
            CommitteeGroupViewModel model = new CommitteeGroupViewModel();
            return View(model);
        }

        // POST: CommitteeGroup/Create
        [HttpPost]
        [CustomAuthentication]
        public ActionResult Create(CommitteeGroupViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.GroupId = CommitteeGroupsBusiness.NewGroupId();
                    bool result = CommitteeGroupsBusiness.AddCommitteeGroup(model);
                    if(result)
                        return RedirectToAction("Index");
                    else
                        return View(model);

                }
            }
            catch
            {
                return View();
            }
            return View();
        }

        // GET: CommitteeGroup/Edit/5
        [CustomAuthentication]
        public ActionResult Edit(int id)
        {
            CommitteeGroupViewModel model = CommitteeGroupsBusiness.DetailsCommitteeGroup(id);
            return View(model);
        }

        // POST: CommitteeGroup/Edit/5
        [HttpPost]
        public ActionResult Edit(CommitteeGroupViewModel model)
        {
            try
            {
                if(model.GroupId>0)
                {
                    CommitteeGroupsBusiness.UpdateCommitteeGroup(model);
                    return RedirectToAction("Index");
                }
                return View();
                //return RedirectToAction("Edit/Id/"+ model.GroupId);
            }
            catch
            {
                return View();
            }
        }

        // GET: CommitteeGroup/Delete/5
        [CustomAuthentication]
        public ActionResult Delete(int id)
        {
            CommitteeGroupViewModel model = CommitteeGroupsBusiness.DetailsCommitteeGroup(id);
            return View(model);
        }

        // POST: CommitteeGroup/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {            
            try
            {
                if(id>0)
                {
                    CommitteeGroupViewModel model = CommitteeGroupsBusiness.DetailsCommitteeGroup(id);
                    bool isAssociated = CommitteeGroupsBusiness.IsGroupAssociatedWithMenber(model.GroupName);
                    if (isAssociated == false)
                    {
                        bool result = CommitteeGroupsBusiness.DeleteCommitteeGroup(model);
                        if (result)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return View(model);
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "This Group is Associated with Some Committee Member, so you can not delete.";
                        return View(model);
                    }
                }
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Test.Web/Controllers/CommitteeMemberController.cs
using SparshWeb.ModelBusiness;
using SparshWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Test.Web.ModelBusiness;
using SparshWeb.CustomAttribute;

namespace SparshWeb.Controllers
{
    public class CommitteeMemberController : Controller
    {
        // GET: CommitteeMember
        [CustomAuthentication]
        public ActionResult Index(int? page)
        {
            List<CommitteeMemberViewModel> list = CommitteeMemberBusiness.GetAllCommitteeMemberList();
            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        // GET: CommitteeMember/Details/5
        [CustomAuthentication]
        public ActionResult Details(int id)
        {
            CommitteeMemberViewModel model = CommitteeMemberBusiness.CommitteeMemberDetails(id);
            return View(model);
        }

        // GET: CommitteeMember/Create
        [CustomAuthentication]
        public ActionResult Create()
        {
            CommitteeMemberViewModel model = new CommitteeMemberViewModel();
            ViewBag.MemberTypeList = new SelectList(CommitteeGroupsBusiness.GetAllCommitteeGroupList(), "GroupId", "GroupName");
            model.Contact = "+91 0000000000";
            model.WhatsUp = "+91 0000000000";
            return View(model);
        }

        // POST: CommitteeMember/Create
        [HttpPost]
        [CustomAuthentication]
        public ActionResult Create(CommitteeMemberViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                bool result = CommitteeMemberBusiness.AddCommitteeMember(model);
                if(result)
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Create", model);
            }
            catch
            {
                return View();
            }
        }

        // GET: CommitteeMember/Edit/5
        [CustomAuthentication]
        public ActionResult Edit(int id)
        {
            CommitteeMemberViewModel model = CommitteeMemberBusiness.CommitteeMemberDetails(id);
            List<CommitteeGroupViewModel> grList = CommitteeGroupsBusiness.GetAllCommitteeGroupList();
            CommitteeGroupViewModel gmodel = CommitteeGroupsBusiness.GetAllCommitteeGroupList().Where(x => x.GroupName == model.MemberGroup).FirstOrDefault();
            model.MemberGroupId = gmodel.GroupId;
            model.NameTitleList = CommitteeMemberBusiness.TitleList();
            var tt = new SelectList(model.NameTitleList, "Name", "Desc", model.Title);            
            var list = new SelectList(grList, "GroupId", "GroupName", gmodel.GroupId);
            ViewBag.MemberTypeList = list;
            ViewBag.TitleList = tt;
            return View(model);
        }

        // POST: CommitteeMember/Edit/5
        [HttpPost]
        [CustomAuthentication]
        public ActionResult Edit(CommitteeMemberViewModel model)
        {
            try
            {
                if(ModelState.IsValid == true && model != null && model.MemderId>0)
                {
                    bool result = CommitteeMemberBusiness.UpdateCommitteeMember(model);
                    if(result)
                        return RedirectToAction("Index");
                    else
                        return View(model);
                }
            }
            catch
            {
                return View();
            }
            return View(model);
        }

        // GET: CommitteeMember/Delete/5
        [CustomAuthentication]
        public ActionResult Delete(int id)
        {
            CommitteeMemberViewModel model = CommitteeMemberBusiness.CommitteeMemberDetails(id);
            return View(model);
        }

        // POST: CommitteeMember/Delete/5
        [HttpPost, ActionName("Delete")]
        [CustomAuthentication]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                CommitteeMemberViewModel model = CommitteeMemberBusiness.CommitteeMemberDetails(id);
                if (model != null && model.MemderId > 0)
                {
                    bool result = CommitteeMemberBusiness.DeleteCommitteeMember(model);
                    if (result)
                        return RedirectToAction("Index");
                    else
                        return View(model);
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }
    }
}

Test.Web/Controllers/WebNoticeController.cs
using SparshWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using SparshWeb.XMLHelper;
using SparshWeb.ModelBusiness;
using SparshWeb.CustomAttribute;

namespace Test.Web.Controllers
{
    public class WebNoticeController : Controller
    {
        // GET: WebNotice
        [CustomAuthentication]
        public ActionResult Index(int? page)
        {
            List<WebNoticeViewModel> wnList = XMLWebNoticeReaderWriter.ReadWebNoticeData();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            wnList = wnList.OrderByDescending(x => x.NoticeId).ToList();
            return View(wnList.ToPagedList(pageNumber, pageSize));
        }

        // GET: WebNotice/Details/5
        [CustomAuthentication]
        public ActionResult Details(int id)
        {
            WebNoticeViewModel model = new WebNoticeViewModel();            
            model = WebNoticeBusiness.GetWebNoticebyId(id);
            return View(model);
        }

        // GET: WebNotice/Create
        [CustomAuthentication]
        public ActionResult Create()
        {
            WebNoticeViewModel model = new WebNoticeViewModel();
            model.PublishedDate = DateTime.Now;
            model.UpdatedDate = DateTime.Now;
            return View(model);
        }

        // POST: WebNotice/Create
        [HttpPost]
        [CustomAuthentication]
        public ActionResult Create(WebNoticeViewModel model)
        {
            try
            {
                if(ModelState.IsValid && WebNoticeBusiness.IsAnyActiveWebNotice() <= 0 )
                {
                    int lastId = WebNoticeBusiness.LastNoticeId();
                    model.NoticeId = lastId + 1;
                    model.UpdatedDate = DateTime.Now;
                    WebNoticeBusiness.ApendWebNotice(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    //ModelState.AddModelError("IsActive", "Already Active Notice is there, Make all other notice inactive.");
                    ViewBag.ErrorMsg = "Already Active Notice is there, Make all other notice inactive and update this.";
                    return View(model);
                }
            }
            catch
            {
                //ModelState.AddModelError("IsActive", "Already Active Notice is there, Make all other notice inactive.");
                //return RedirectToAction("Create");
            }
            return View(model);
        }

        // GET: WebNotice/Edit/5
        [CustomAuthentication]
        public ActionResult Edit(int id)
        {
            WebNoticeViewModel model = XMLWebNoticeReaderWriter.GetWebNoticeDetails(id);
            return View(model);
        }

        // POST: WebNotice/Edit/5
        [HttpPost]
        [CustomAuthentication]
        public ActionResult Edit(WebNoticeViewModel model)
        {
            try
            {
                model.UpdatedDate = DateTime.Now;
                bool result = XMLWebNoticeReaderWriter.UpdateWebNotice(model);
                if(result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

                
            }
            catch
            {
                
            }
            return View();
        }

        // GET: WebNotice/Delete/5
        [HttpGet]
        [CustomAuthentication]
        public ActionResult Delete(int id)
        {
            WebNoticeViewModel model = new WebNoticeViewModel();
            model = WebNoticeBusiness.GetWebNoticebyId(id);
            return View(model);
        }

        // POST: WebNotice/Delete/5
        [HttpPost, ActionName("Delete")]
        [CustomAuthentication]
        public ActionResult DeleteConformed(int id)
        {
            try
            {
                WebNoticeViewModel model = new WebNoticeViewModel();
                model = WebNoticeBusiness.GetWebNoticebyId(id);
                //model.NoticeId = 1013;
                WebNoticeBusiness.DeleteWebNotice(model);
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Test.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/stylesMenu.css">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <link href="~/Content/Custom.css" rel="stylesheet" />
   
    <script src="js/bootstrap.js"></script>
    <title>@ViewBag.Title - Sparsh</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body style="height:100%; width:auto; background-repeat: no-repeat;background-size: cover;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#aa" aria-expanded="false">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @*@Html.ActionLink("Applicationn name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                    <img src="~/Images/logo.png" style=" width:25%; height:25%; background-repeat:no-repeat;" />
                </div>
                <div class="navbar-collapse collapse" id="aa">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Notice", "NoticeBoard", "Home")</li>
                        <li>@Html.ActionLink("Members", "Members", "Home")</li>
                        <li>@Html.ActionLink("PujaCommittee", "PujaCommittee", "Home")</li>
                        <li>@Html.ActionLink("Gallery", "Gallery", "Home")</li>
                        <li>@Html.ActionLink("Yearly Schedule", "YearlySchedule", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            @*<footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
            <footer>
                <p style="font-weight:100;">@*Total Number of visitors: @ApplicationInstance.Application["Totaluser"]*@</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>

</html>

Test.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/stylesMenu.css">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <link href="~/Content/SiteAdmin.css" rel="stylesheet" />
    <title>@ViewBag.Title - Sparsh</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <div id='cssmenu'>
        <ul>
            <li><a href="@Url.Action("Index", "Admin")"><span>Admin</span></a></li>
            <li class='active has-sub'>
                <a href="#"><span>Notice Board</span></a>
                <ul>
                    <li class='has-sub'>
                        <a href="@Url.Action("Index", "WebNotice")"><span>Web Notice</span></a>
                        @*<ul>
                                <li><a href="@Url.Action("Contact", "Admin")"><span>Sub Product 1</span></a></li>
                                <li class='last'><a href='@Url.Action("About", "Home")'><span>Sub Product 2</span></a></li>
                            </ul>*@
                    </li>
                    <li class='has-sub'>
                        <a href="@Url.Action("SMSNotice", "Admin")"><span>SMS Notice</span></a>
                        @*<ul>
                                <li><a href='#'><span>Sub Product</span></a></li>
                                <li class='last'><a href='#'><span>Sub Product</span></a></li>
                            </ul>*@
                    </li>
                    <li class='has-sub'><a href="#"><span>About Us - Update</span></a></li>
                </ul>
            </li>
            <li class='active has-sub'>
                <a href="#"><span>Committee</span></a>
                <ul>
                    <li class='has-sub'>
                        <a href="@Url.Action("Index", "CommitteeGroup")"><span>Committee Group</span></a>
                    </li>
                    <li class='has-sub'>
                        <a href="@Url.Action("Index", "CommitteeMember")"><span>Committee Members</span></a>
                    </li>
                    <li class='has-sub'><a href="#"><span>To DO ..</span></a></li>
                </ul>
            </li>
            <li class='last'><a href='#'><span>Contact</span></a></li>
        </ul>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>

</html>

Test.Web/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/Content/stylesMenu.css">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <link href="~/Content/Custom.css" rel="stylesheet" />
    <title>@ViewBag.Title - Sparsh</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body style="height:100%; width:auto; background-repeat: no-repeat;background-size: cover;">
    
    <div class="container body-content">        
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>